article: https://www.bigclown.com/doc/projects/radio-push-button/
video: https://youtu.be/OCPPKXzCBg0
images:
  - url: https://github.com/hardwario/website/blob/master/static/kits-images/push-button/main.png
articles:
  - title: HARDWARIO IoT Kit Light Control of LED Strip
    url: https://www.hackster.io/159159/hardwario-iot-kit-light-control-of-led-strip-7fe73c
    description: Control colored lights in your room with HARDWARIO. Lights are controlled by orientation of Push button kit or by button itself.
    images:
      - url: https://hackster.imgix.net/uploads/attachments/1050360/_fbE0JXjbPm.blob?auto=compress%2Cformat&w=900&h=675&fit=min
  - title: Wireless Presenter with Accelerometer
    url: https://www.hackster.io/161479/wireless-presenter-with-accelerometer-962318
    description: Have your own presenter always with you. You can make wireless one with HARDWARIO and their Push Button Kit. Just follow these instructions.
    images:
      - url: https://hackster.imgix.net/uploads/attachments/1050361/_d61Iu6dTDX.blob?auto=compress%2Cformat&w=900&h=675&fit=min
  - title: Egg Timer with a Push Button Kit
    url: https://www.hackster.io/160619/egg-timer-with-a-button-kit-fc869a
    description: Have your eggs always perfectly boiled just as you like them. With this solution that is simple and customizable.
    images:
      - url: https://hackster.imgix.net/uploads/attachments/1050370/_KhfpefJi2Y.blob?auto=compress%2Cformat&w=900&h=675&fit=min
  - title: Make Your "Dumb" Lamp Smarter
    url: https://www.hackster.io/jakub-smejkal/make-your-dumb-lamp-smarter-ce64a7
    description: Make your ordinary lamp a smart one with just a few steps. You can achieve that with HARDWARIO IoT Kit and NETIO smart socket.
    images:
      - url: https://hackster.imgix.net/uploads/attachments/1050351/_q6fyfhHjHg.blob?auto=compress%2Cformat&w=900&h=675&fit=min
  - title: Night Lamp with Wireless Buttons and Motion Detector
    url: https://www.hackster.io/hubmartin/night-lamp-with-wireless-buttons-and-motion-detector-1c32e8
    description: Put smart LED strip to the lamp, under bed. Control intensity with a knob or wirelessly with push button or motion detector.
    video: https://hackster.imgix.net/uploads/attachments/732203/bigclown_night_lamp_53ALljpY8c.gif?auto=compress&gifq=35&w=900&h=675&fit=min&fm=mp4
assembly:
  - name: HARDWARIO Button Module
  - name: HARDWARIO Core Module
  - name: HARDWARIO Mini Battery Module
